[project]
name = "alldog-mjlab"
version = "0.1.0"
description = "XJTUROBOCON 四足组 机器人强化学习训练仓库"
readme = "README.md"
authors = [
    { name = "wind", email = "zeyuqin@foxmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mjlab>=1.6.0",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[project.entry-points."mjlab.tasks"]
alldog_mjlab = "alldog_mjlab"
